backend:
  name: git-gateway
  branch: master

media_folder: src/media # アップロードファイルの保存場所
public_folder: /media

collections:
  - name: "home"
    label: "Home"
    files:
      - file: "src/pages/index.md"
        label: "トップページ"
        name: "index"
        fields:
          - { label: "Template", name: "template", widget: "hidden", default: "HomeTemplate"}
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    editor:
      preview: true # プレビュー表示を有効化
    publish_mode: editorial_workflow # ワークフロー管理を有効化
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Template", name: "template", widget: "select", options: ["BlogTemplate"]}
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }